/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.85 95/04/24 10:48:47 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 19
#define YY_END_OF_BUFFER 20
static yyconst short int yy_acclist[26] =
    {   0,
       20,   18,   19,   19,   18,   19,   18,   19,    1,   12,
        4,   16,   10,    8,    6,    2,   13,    5,   14,   17,
       11,    9,    7,    3,   15
    } ;

static yyconst short int yy_accept[177] =
    {   0,
        1,    1,    1,    1,    1,    2,    4,    5,    7,    9,
        9,    9,    9,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   13,   13,   14,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   16,   16,   16,   16,
       16,   16,   17,   17,   17,   17,   17,   17,   17,   17,

       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   19,   19,   19,   20,   20,   20,
       20,   20,   20,   20,   21,   21,   22,   23,   23,   23,
       23,   23,   23,   23,   24,   24,   25,   25,   25,   25,
       25,   25,   25,   25,   26,   26
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    6,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    7,    8,    9,   10,   11,    5,
       12,   13,   14,    5,    5,   15,   16,   17,   18,   19,
        5,   20,   21,   22,   23,    5,    5,   24,    5,    5,
        5,    5,    5,    5,    5,    5,    7,    8,    9,   10,

       11,    5,   12,   13,   14,    5,    5,   15,   16,   17,
       18,   19,    5,   20,   21,   22,   23,    5,    5,   24,
        5,    5,    5,    5,    5,    5,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[25] =
    {   0,
        1,    2,    3,    4,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5
    } ;

static yyconst short int yy_base[203] =
    {   0,
      287,    0,    0,    0,  289,  291,  291,  284,    0,  283,
      283,  281,  291,  280,  279,    6,    0,    0,  264,  264,
      262,  272,  267,  270,  260,  252,  252,  261,  252,  264,
      250,    3,  261,  257,  253,  259,  250,  257,  245,  247,
      246,  248,  250,  242,    0,  248,  239,  244,  243,  242,
      245,  240,  247,  227,    0,  224,  243,  226,  230,  222,
      239,  231,  238,    0,  221,    0,    0,  228,  234,  217,
      232,  232,  214,  230,  229,  211,  226,    0,  225,  224,
      216,  222,  221,    0,  220,  220,  218,  217,  211,  215,
      214,  214,  212,  211,  210,  209,  198,  207,  206,  205,

        0,  204,  203,  202,  184,  200,  199,  198,    3,  197,
        0,  196,  185,  194,  191,  188,   10,  182,   25,    0,
      164,    0,    0,  175,   28,   21,  169,   31,   32,  152,
       35,   36,  159,  156,    0,   39,   42,   44,    0,   45,
       48,    0,   49,  150,   52,   55,  148,   57,   60,   62,
       65,   67,   68,  142,  137,  131,  128,   71,   74,   77,
      123,   79,   82,  103,   70,   24,   13,    7,    0,   84,
       85,   88,   91,    4,  291,   94,   99,  104,  106,  108,
      110,  112,  114,  116,  118,  123,  128,  132,  137,  142,
      147,  151,  156,  160,  162,  166,  170,  175,  179,  183,

      188,  192
    } ;

static yyconst short int yy_def[203] =
    {   0,
      176,  176,  177,  177,  175,  175,  175,  175,  178,  175,
      178,  175,  175,  175,  175,  175,   16,  175,  175,  175,
      175,  175,  175,  175,  175,  175,  175,  175,  175,  175,
      175,  175,  175,  175,  175,  175,  175,  175,  175,  175,
      175,  175,  175,  175,  179,  175,  175,  175,  175,  175,
      175,  175,  179,  175,  180,  175,  175,  175,  175,  175,
      175,  175,  180,  181,  175,  182,  183,  175,  175,  175,
      175,  181,  175,  182,  183,  175,  175,  184,  175,  175,
      175,  175,  175,  185,  175,  184,  175,  175,  175,  175,
      175,  185,  175,  175,  175,  175,  175,  175,  175,  175,

      186,  175,  175,  175,  175,  175,  175,  175,  175,  175,
      187,  175,  175,  175,  175,  175,  188,  175,  175,  189,
      175,  190,  191,  175,  188,  188,  175,  192,  175,  175,
      175,  175,  175,  175,  193,  192,  192,  194,  195,  196,
      197,  198,  175,  175,  194,  194,  195,  196,  196,  197,
      197,  175,  199,  175,  175,  175,  175,  200,  199,  199,
      175,  200,  200,  175,  175,  175,  175,  175,  201,  175,
      202,  202,  202,  175,    0,  175,  175,  175,  175,  175,
      175,  175,  175,  175,  175,  175,  175,  175,  175,  175,
      175,  175,  175,  175,  175,  175,  175,  175,  175,  175,

      175,  175
    } ;

static yyconst short int yy_nxt[316] =
    {   0,
      175,  175,    7,    8,  117,    9,  117,  161,    9,   17,
      169,  117,   24,  125,   18,   19,  168,   25,   39,   20,
       21,   40,  175,  134,   22,   23,  128,  108,  128,  117,
      134,  125,  128,  138,  136,  138,  140,  141,  140,  141,
      128,  144,  136,  175,  144,  138,  140,  145,  148,  141,
      153,  150,  153,  138,  154,  145,  175,  154,  140,  156,
      148,  175,  156,  141,  157,  150,  175,  157,  158,  153,
      158,  159,  158,  167,  162,  153,  164,  159,  175,  164,
      158,  166,  162,  175,  166,  171,  171,  171,  172,  171,
      174,  172,  175,  174,    6,    6,    6,    6,    6,    7,

        7,    7,    7,    7,   11,   11,  102,   11,   11,   53,
       53,   63,   63,   72,   72,   74,   74,   75,   75,   86,
       86,   92,   92,  109,  109,  109,  165,  109,  119,  119,
      119,   91,  119,  126,   90,  126,  126,  129,  129,  129,
      161,  129,  131,  131,  131,   88,  131,  132,  132,  132,
      155,  132,  137,   79,  137,  137,  143,  143,  143,   69,
      143,  146,  142,  146,  146,  147,  147,  149,  139,  149,
      149,  151,  135,  151,  151,  152,  152,  152,  133,  152,
      160,  130,  160,  160,  163,  127,  163,  163,  170,  170,
      170,  124,  170,  173,  123,  173,  173,  122,  121,  120,

      118,  116,  115,  114,  113,  112,  111,  110,  108,  107,
      106,  105,  104,  103,  102,  101,  100,   99,   98,   97,
       96,   95,   94,   93,   91,   90,   89,   88,   87,   85,
       84,   83,   82,   81,   80,   79,   78,   77,   76,   73,
       71,   70,   69,   68,   67,   66,   65,   64,   62,   61,
       60,   59,   58,   57,   56,   55,   54,   52,   51,   50,
       49,   48,   47,   46,   45,   44,   43,   42,   41,   38,
       37,   36,   35,   34,   33,   32,   31,   30,   29,   28,
       27,   26,   16,   15,   14,   13,   12,   10,  175,    7,
        5,  175,  175,  175,  175,  175,  175,  175,  175,  175,

      175,  175,  175,  175,  175,  175,  175,  175,  175,  175,
      175,  175,  175,  175,  175
    } ;

static yyconst short int yy_chk[316] =
    {   0,
        0,    0,    2,    2,  109,    2,  109,  174,    2,   16,
      168,  117,   18,  117,   16,   16,  167,   18,   32,   16,
       16,   32,  126,  126,   16,   16,  119,  166,  119,  125,
      125,  125,  128,  129,  128,  129,  131,  132,  131,  132,
      136,  136,  136,  137,  137,  138,  140,  138,  140,  141,
      143,  141,  143,  145,  145,  145,  146,  146,  148,  148,
      148,  149,  149,  150,  150,  150,  151,  151,  152,  153,
      152,  153,  158,  165,  158,  159,  159,  159,  160,  160,
      162,  162,  162,  163,  163,  170,  171,  170,  171,  172,
      172,  172,  173,  173,  176,  176,  176,  176,  176,  177,

      177,  177,  177,  177,  178,  178,  164,  178,  178,  179,
      179,  180,  180,  181,  181,  182,  182,  183,  183,  184,
      184,  185,  185,  186,  186,  186,  161,  186,  187,  187,
      187,  157,  187,  188,  156,  188,  188,  189,  189,  189,
      155,  189,  190,  190,  190,  154,  190,  191,  191,  191,
      147,  191,  192,  144,  192,  192,  193,  193,  193,  134,
      193,  194,  133,  194,  194,  195,  195,  196,  130,  196,
      196,  197,  127,  197,  197,  198,  198,  198,  124,  198,
      199,  121,  199,  199,  200,  118,  200,  200,  201,  201,
      201,  116,  201,  202,  115,  202,  202,  114,  113,  112,

      110,  108,  107,  106,  105,  104,  103,  102,  100,   99,
       98,   97,   96,   95,   94,   93,   92,   91,   90,   89,
       88,   87,   86,   85,   83,   82,   81,   80,   79,   77,
       76,   75,   74,   73,   72,   71,   70,   69,   68,   65,
       63,   62,   61,   60,   59,   58,   57,   56,   54,   53,
       52,   51,   50,   49,   48,   47,   46,   44,   43,   42,
       41,   40,   39,   38,   37,   36,   35,   34,   33,   31,
       30,   29,   28,   27,   26,   25,   24,   23,   22,   21,
       20,   19,   15,   14,   12,   11,   10,    8,    5,    1,
      175,  175,  175,  175,  175,  175,  175,  175,  175,  175,

      175,  175,  175,  175,  175,  175,  175,  175,  175,  175,
      175,  175,  175,  175,  175
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
char *yytext;
#line 1 "scan_commons.l"
#define INITIAL 0
#line 2 "scan_commons.l"
#ifndef lint
static char rcsId[]="$Header: /usr/local/rcs/ForUtil/Commons/RCS/scan_commons.l,v 1.9 1996/08/28 17:44:20 koen Exp koen $";
#endif
/*****
* scan_commons.l : database builder for stuff defined in common blocks
*
* This file Version	$Revision: 1.9 $
*
* Creation date:	Fri Mar 15 18:02:11 GMT+0100 1996
* Last modification: 	$Date: 1996/08/28 17:44:20 $
* By:			$Author: koen $
* Current State:	$State: Exp $
*
* Author:		koen
* (C)Copyright 1995-1996 Ripley Software Development
* All Rights Reserved
*
* This program has three undocumented switches for debugging purposes:
* -c: dump core on errors
* -t: do not install signal traps, needed for debugging
* -m for memory information under msdos
*****/
/*****
* ChangeLog 
* $Log: scan_commons.l,v $
* Revision 1.9  1996/08/28 17:44:20  koen
* Added print_version_id
*
* Revision 1.8  1996/08/27 19:13:29  koen
* Changed scanner routines to support scanning of source files.
*
* Revision 1.7  1996/08/07 21:11:04  koen
* Updated the rules and added a rule for PARAMETER
*
* Revision 1.6  1996/08/02 14:49:29  koen
* moved all system dependencies to lib/sysdeps.h
*
* Revision 1.5  1996/07/30 01:58:16  koen
* Changed rule for common blocks to use every possible char as a 
* continuation character. 
* Implemented the ignore_this_file routine. 
* Reorganized output stuff and command line handling. 
* Added version information.
*
* Revision 1.4  1996/07/16 00:38:14  koen
* minor (cosmetic) changes.
*
* Revision 1.3  1996/05/06 00:33:02  koen
* Adapted for MSDOS. Added some showing of files to scan when -v is used.
*
* Revision 1.2  1996/04/25 02:27:04  koen
* Cleanup and comments added.
*
* Revision 1.1  1996/03/15 04:16:42  koen
* Initial Revision
*
*****/ 
#ifdef HAVE_CONFIG_H
#include "autoconf.h"
#endif

#include <signal.h>

#include "lib_commons.h"
#include "forutil.h"
#include "memmacros.h"
#include "version.h"

#define MAXDIRS		64
#define MAXIGNORE	64
#define MAXEXTS		8

#define YY_EXIT_FAILURE	13

/****
* Local variables
****/
datum content;
int verbose;
static char progname[32];
static int quiet, full_names, replace, dump_core, no_signal;
static int num_total, num_total_accepted, num_total_rejected;
static int num_total_replaced, num_total_stored;
static int num_common_total, num_common_rejected, num_common_accepted;
static int num_common_replaced, num_common_stored, fast;
static int reorganize, curr_file_num, ign_file_num;
static char *outfile;
static char curr_path[512], curr_file[128];
static int num_dirs_to_visit, num_extensions, num_ignore;
static char *dirs_to_visit[MAXDIRS];
static char *ext_table[MAXEXTS];
static char *ignore_list[MAXIGNORE];

int num_files;
static int num_warnings, num_errors;
char **file_list;

#ifdef __MSDOS__
unsigned long dir_mem, ext_mem, file_mem, ign_mem;
static int need_mem_info_for_msdos;
#endif

/* the database file */
static GDBM_FILE db_file;

/****
* Local function prototypes
****/
static void get_common_contents(char *text);

static void (*gdbm_proto_func)();	/* generic gdbm insertion proto */
static void replace_item(datum key);	/* replace & update an item */
static void insert_item(datum key);	/* insert an item */

static char *usage = {"Usage: %s [-afhqrsv] [-Eext] [-Idir] [-ddatabase] [-xname] [files]\n\n"
" Scan f77 include files for commons and stores them for use with get_common\n"
"\n Options:\n"
"\t-a: add instead of rejecting duplicate commons in different files\n"
"\t-f: Store filenames only. Default is full filenames.\n"
"\t-h, --help: print this help\n"
"\t-q: be really quiet (usefull if called from a script)\n"
"\t-r: re-organize after updating. This may take a _long_ time.\n"
"\t-s: safe operation, resync database after each update (safe but slower)\n"
"\t-v: verbose\n"
"\t--version: display version number\n"
"\t-E[ext] : extensions to use when searching files. Multiple -E allowed\n"
"\t          Use -E- to specify no extension.\n"
"\t-I[dir] : get files from directory dir. Multiple -I allowed\n"
"\t-d[database]: name of database to create/update\n"
"\t-x[name]: name of file to ignore when scanning directories\n"
" Using -f can help reduce the size of the created database.\n"
" To automate updates, scan_commons looks at the value of the environment\n"
" variable COMMON_DATABASE if no database is given.\n\n"
"(C)Copyright 1995-1996 by Ripley Software Development\n"};

/****
* A Note on the regular expressions used.
*
* We scan for a number of defined types in common include files.
* (common, character, real and logical)
* The scanning sequence is as follows:
* 1. A scan is made for lines containing the COMMON, LOGICAL, REAL,
*    DOUBLE, COMPLEX and CHARACTER keywords. These lines must begin with
*    at least 6 spaces and must be followed by characters defining that param.
*    The contents of the text found are scanned for ``real'' definitions by 
*    get_common_contents
* 
* 2. When step 1 is complete, a further scan is done to see if the
*    common block found has continuation lines, identified by the 
*    BEGIN GETBLOCK statement. 
*    All lines following any of the keywords mentioned above that begin
*    with five spaces and a continuation character contain additional
*    contents of that parameter block and are picked up by the scanner.
*
* The ``+'' after both regexp tells lex it must match one or more of these
* regular expressions. 
*****/
#define GETBLOCK 1

#line 667 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 177 "scan_commons.l"

#line 819 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 176 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 291 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 178 "scan_commons.l"
BEGIN(INITIAL);
	YY_BREAK
case 2:
#line 181 "scan_commons.l"
case 3:
YY_RULE_SETUP
#line 181 "scan_commons.l"
{
			get_common_contents(yytext);
			BEGIN 0;
		}
	YY_BREAK
case 4:
#line 186 "scan_commons.l"
case 5:
YY_RULE_SETUP
#line 186 "scan_commons.l"
{
			get_common_contents(yytext);
			BEGIN 0;
		}
	YY_BREAK
case 6:
#line 191 "scan_commons.l"
case 7:
YY_RULE_SETUP
#line 191 "scan_commons.l"
{
			get_common_contents(yytext);
			BEGIN 0;
		}
	YY_BREAK
case 8:
#line 196 "scan_commons.l"
case 9:
YY_RULE_SETUP
#line 196 "scan_commons.l"
{
			get_common_contents(yytext);
			BEGIN 0;
		}
	YY_BREAK
case 10:
#line 201 "scan_commons.l"
case 11:
YY_RULE_SETUP
#line 201 "scan_commons.l"
{
			get_common_contents(yytext);
			BEGIN 0;
		}
	YY_BREAK
case 12:
#line 206 "scan_commons.l"
case 13:
YY_RULE_SETUP
#line 206 "scan_commons.l"
{
			get_common_contents(yytext);
			BEGIN 0;
		}
	YY_BREAK
case 14:
#line 211 "scan_commons.l"
case 15:
YY_RULE_SETUP
#line 211 "scan_commons.l"
{
			get_common_contents(yytext);
			BEGIN 0;
		}
	YY_BREAK
case 16:
#line 216 "scan_commons.l"
case 17:
YY_RULE_SETUP
#line 216 "scan_commons.l"
{
			get_common_contents(yytext);
			BEGIN 0;
		}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 220 "scan_commons.l"
BEGIN(INITIAL);
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(GETBLOCK):
#line 221 "scan_commons.l"
{
		yyterminate();
		}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 224 "scan_commons.l"
ECHO;
	YY_BREAK
#line 1013 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 176 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 176 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	*yy_state_ptr++ = yy_current_state;
	yy_is_jam = (yy_current_state == 175);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yytext_ptr = yy_c_buf_p;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p =
						yytext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in yyinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');
	if ( yy_current_buffer->yy_at_bol )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *str )
#else
YY_BUFFER_STATE yy_scan_string( str )
yyconst char *str;
#endif
	{
	int len;
	for ( len = 0; str[len]; ++len )
		;

	return yy_scan_bytes( str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n - YY_MORE_ADJ; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 224 "scan_commons.l"


/****
* macro used in the signal catcher routine below.
* aborts the scanner if yyin is still open and, if needed,
* closes the current database file.
****/
#define SHUTUP(text,exitnum)	{ \
	fprintf(stderr, "\n%s: %s\n", progname, text); \
	if(yyin) \
	{ \
		fprintf(stderr, "Stopping scanner\n"); \
		YY_FLUSH_BUFFER; \
		fclose(yyin); fclose(yyout); \
	} \
	if(db_file) \
	{ \
		fprintf(stderr, "Syncing and closing database\n");\
		gdbm_close(db_file); db_file = NULL; \
	} \
	fprintf(stderr, "Terminated with signal %s\n", #exitnum); \
	fprintf(stderr, "Total files scanned: %i\n", curr_file_num); \
	if(dump_core) abort(); \
	exit(exitnum+20); \
	}

/****
* Exit function for internal flex errors. This function will
* close the database file (if left open)
****/
void
scanner_fail(void)
{
#if 0
	if(db_file)
	{
		gdbm_close(db_file);
		db_file = NULL;
	}
	fclose(yyin);
	fclose(yyout);
#endif
}
/****
* Signal handler for a nice and clean exit 
****/
static RETSIGTYPE
sig_handler(int signum)
{
	switch(signum)
	{
#ifdef SIGBUS	/* SIGBUS is not defined on all systems */
		case SIGBUS:
			SHUTUP("Aaaiieee, a bus error!", SIGBUS);
#endif /* SIGBUS */
		case SIGSEGV:
			SHUTUP("Ooops, a segmentation violation.", SIGSEGV);
#ifdef SIGALRM	/* same for SIGALRM */
		case SIGALRM:
			SHUTUP("Aborted.", SIGALRM);
#endif
		case SIGUSR1:
			SHUTUP("Memory allocation error.", SIGUSR1);
#ifdef SIGQUIT	/* same for SIGQUIT */
		case SIGQUIT:
			SHUTUP("Interrupted.", SIGQUIT);
#endif
		case SIGINT:
			SHUTUP("Interrupted.", SIGINT);
		default:
			SHUTUP("What did _you_ do?  Stopping.", signum);
	}
}

/*****
* replace an existing entry in the current database with the data contained
* in key. Otherwise create a new entry in the database.
*****/
static void replace_item(datum key)
{
	if(gdbm_exists(db_file, key))
	{
		datum prev;

		prev = gdbm_fetch(db_file, key);
		/*
		* If the stringcompare matches the current file, it's already 
		* here so we don't want to update it again. 
		*/
		if(strstr(prev.dptr, content.dptr))
		{
			num_common_rejected++;
			return;
		}
		/*
		* Resize the returned item so it will contain the next also 
		* but separated by a comma 
		*/
		prev.dsize += content.dsize + 2;
		checked_realloc(prev.dptr, prev.dsize, char);

		/* update data */
		strcat(prev.dptr, ",");
		strcat(prev.dptr, content.dptr);

		/* store the new data */
		gdbm_store(db_file, key, prev, GDBM_REPLACE);

		free(prev.dptr);
		num_common_accepted++;
		num_common_stored++;
		num_common_replaced++;
		return;
	}	/* fall through */
	insert_item(key);
}

/*****
* Add a new entry to the current database
*****/
static void insert_item(datum key)
{
	if(gdbm_store(db_file, key, content, GDBM_INSERT))
	{
		if(!verbose)
			printf("already have %s, rejected.\n", key.dptr);
		num_common_rejected++;
		return;
	}	/* fall through */
	num_common_accepted++;
	num_common_stored++;
}

/*****
* retrieve all commons found in text
*****/
static void
get_common_contents(char *text)
{
	char *chPtr, *block;
	int i;
	datum key;

	/* allocate scratch memory */
	checked_malloc(block, strlen(text)+1, char);
	/* 
	* must copy, text is a ptr into a buffer of the scanner. 
	* Modifying this block will cause unpredictable results 
	*/
	strcpy(block, text);
	/* make all text upcase */
	upcase(block);

	/* 
	* forget blocks with FUNCTION in them, scanner picked up the
	* wrong line.
	*/
	if(strstr(block, "FUNCTION"))
		return;

	/* scan the block for commons. scan_block returns 0 on error. */
	if((num_warnings = scan_block(block, yylineno)) != -1)
	{
		/* store the commons returned */
		for(i=0, chPtr = strtok(block, ","); chPtr != NULL; 
			chPtr = strtok(NULL, ","), i++)
		{
			key.dptr = chPtr;
			key.dsize = strlen(chPtr)+1;
			/*
			* gdbm_proto_func is a ptr to the actual function used. 
			* It's real value depends on the -a command line option 
			*/
			gdbm_proto_func(key); 
			num_common_total++; 
		}
	}
	else
		num_errors++;
	/* if we got warnings, display in what file they are found */
	if(num_warnings)
		fprintf(stderr, "File: %s%s\n", curr_path, curr_file);
	free(block);
}

/*****
* Command line handling
*****/
int set_global_option(char *arg)
{ 
	switch(arg[0])
	{
		case 'a' :	/* add instead of reject commons */
			printf("adding instead of rejecting duplicate "
				"commons\n");
			replace = GDBM_REPLACE;
			gdbm_proto_func = replace_item;
			break;
		case 'c' :	/* dump core on errors */
			dump_core = 1;
			break;
		case 'f' :	/* use filenames instead of full paths */
			full_names = 0 ;
			break;
		case 'h' :	/* help requested */
			printf(usage, progname); 
			exit(2); 
#ifdef __MSDOS__
		case 'm' :	/* show memory usage under msdos */
			need_mem_info_for_msdos = 1;
			break;
#endif
		case 'q' : 	/* be really quiet */
			quiet = 1; 
			verbose = 0; 
			break; 
		case 'r' :	/* re-organize database */
			reorganize = 1;
			break;
		case 's' :	/* fast store. No update after each add */
			fast = 0;
			break;
		case 't' :	/* don't install signal handlers */
			no_signal = 1;
			break;
		case 'v' : 	/* be verbose */
			verbose = 1; 
			break; 
		case 'E' :	/* an extension specification */
			SCAN_ARG("-E");
			if(num_extensions == MAXEXTS)
			{
				fprintf(stderr, "Capacity exceeded, more than "
					"%i extensions given on command "
					"line.\n", MAXEXTS);
				fprintf(stderr, "Ignoring extension %s\n", 
					arg+1);
			}
			else
			{
				checked_malloc(ext_table[num_extensions], 
					strlen(arg+1)+1,char);
				strcpy(ext_table[num_extensions++], arg+1); 
#ifdef __MSDOS__ 	/* dos returns uppercase when building a filelist */
				upcase(ext_table[num_extensions-1]);
#endif
			}
			return(1); 
		case 'I' :	/* a directory specification */
			SCAN_ARG("-I");
			if(num_dirs_to_visit == MAXDIRS)
			{
				fprintf(stderr, "Capacity exceeded, more than "
					"%i directories given on command "
					"line.\n", MAXDIRS);
				fprintf(stderr, "Ignoring directory %s\n", 
					arg+1);
			}
			else
			{
				checked_malloc(dirs_to_visit[num_dirs_to_visit],
					strlen(arg+1)+1, char);
				strcpy(dirs_to_visit[num_dirs_to_visit++], 
					arg+1); 
			}
			return(1); 
		case 'd' :	/* name of database to create/update */
			SCAN_ARG("-d");
			outfile = arg + 1;
			return(1); 
		case 'x' :	/* ignore file specification */
			SCAN_ARG("-x");
			if(num_ignore == MAXIGNORE)
			{
				fprintf(stderr, "Capacity exceeded, more than "
					"%i ignores given on command line.\n", 
					MAXIGNORE);
				fprintf(stderr, "Ignoring option -x%s\n", 
					arg+1);
			}
			else
			{
				checked_malloc(ignore_list[num_ignore], 
					strlen(arg+1)+1, char);
				strcpy(ignore_list[num_ignore++], arg+1);
#ifdef __MSDOS__ /* dos returns uppercase when building a filelist */
				upcase(ignore_list[num_ignore-1]);
#endif
			}
			return(1);
		case '-' :	/* secondary options */
			if(!strcmp("help", arg+1))	/* help wanted */
			{
				printf(usage, progname); 
				exit(2); 
			}
			if(!strcmp("version", arg+1))	/* version number */
			{
				print_version_id(progname, VERSION, "$Revision: 1.9 $");
				exit(2);
			}	/* fall through */
		default:
			fprintf(stderr,"unknown option -%s\n", arg);
			exit(3);
	}
	return(0); 
}

/*****
* Return 0 if the file given is to be ignored, something else otherwise
*****/
static inline int 
ignore_this_file(char *file)
{
	register int i;
	char *ret_val = NULL;
	for(i = 0 ; i < num_ignore &&
		(ret_val = strstr(file, ignore_list[i])) == NULL; i++)
			/* do nothing */ ;
	if(ret_val != NULL)
	{
		if(!quiet)
			printf("Ignoring file %s\n", file);
		ign_file_num++;
		return(0);
	}
	return(1);
}

/*****
* main for scan_commons
*****/
int main (int argc, char **argv)
{ 
	FILE *file;
	int i, narg;
	char *arg;
	char fullname[MAXPATHLEN];

	get_filename_part(argv[0], progname);

	if(argc == 1)
	{
		printf(usage, progname);
		exit(2);
	}

	/*
	* Command line handling. Set default switches.
	*/
	full_names = 1;
	replace = GDBM_INSERT;
	fast = GDBM_FAST;
	/* default action is to insert a common if it does not yet exist */
	gdbm_proto_func = insert_item;

	/* scan the entire command line for any options */
	arg = argv[narg = 1];
	while ( narg < argc && arg[0] == '-' )
	{
		if (arg[0] == '-')
		{
			int num_opts = strlen(arg) ;
			for(i = 1 ; i < num_opts ; i++ )
			if(set_global_option(++arg))
				break;
		}
		arg = argv[++narg];
	}
	/*
	* Try to get a database name from the environment specification if no
	* database is given on the command line
	*/
	if(outfile == NULL)
		outfile = get_database_location(COMMON_LOCATION);
	if(outfile == NULL)
	{
		fprintf(stderr, "%s: no database found/specified\n", progname);
		exit(5);
	}

	/* attach signal handlers if not in debug mode. */
	if(!no_signal)
		ATTACH_SIGNALS;

	/* see if we have a dir spec or files on the command line */
	if(num_dirs_to_visit == 0 && narg == argc && reorganize == 0 )
	{
		fprintf(stderr,"%s: no files given.\n", progname);
		exit(4);
	}

	/* report initial settings if we have to be verbose */
	if(verbose)
	{
		if(num_dirs_to_visit != 0)
		{
			printf("List of directories to visit:\n");
			for(i = 0 ; i < num_dirs_to_visit; i++)
				printf("%s\n", dirs_to_visit[i]);
		}
		if(num_extensions != 0)
		{
			printf("List of extensions to use:\n");
			for(i = 0 ; i < num_extensions; i++)
				printf("%s ", ext_table[i]);
			printf("\n");
		}
		if(num_ignore != 0)
		{
			printf("List of files to ignore:\n");
			for(i = 0 ; i < num_ignore; i++)
				printf("%s\n", ignore_list[i]);
		}
		if(num_dirs_to_visit != 0)
			printf("Scanning directories\n");
		fflush(stdout);
	}

	/* go create a list of all files in the directories given (if any) */
	for(i = 0 ; i < num_dirs_to_visit; i++)
	{
		if(verbose)
			printf("%s\n", dirs_to_visit[i]); 
		build_file_list(&file_list, &num_files, dirs_to_visit[i],
			ext_table, num_extensions); 
	}

	/* add files given on the command line to the list of files to visit */
	if(narg != argc)
	{
		for(i = narg ; i < argc ; i++)
		{
			checked_realloc(file_list, num_files+1, char*);
			checked_malloc(file_list[num_files], strlen(argv[i])+1,
				char);
			sprintf(file_list[num_files++], "%s", argv[i]); 
		}
		if(verbose && argc-narg !=0)
			printf("%i files given on command line.", argc - narg); 
	}

	/* give the list of files to scan when we are being verbose */
	if(verbose)
	{
		printf("List of files to scan:\n");
		for(i = 0 ; i < num_files; i++)
			printf("%s\n", file_list[i]);
	}

	/* show number of files to scan */
	if(!quiet)
	{
		printf("Total Files to scan: %i\n", num_files); 
		printf("Database to create/update: %s\n", outfile);
	}
	fflush(stdout);

	/* open the database file for storage. Set to fast mode if requested */
	db_file = gdbm_open(outfile, 256, GDBM_WRCREAT | fast, DBM_PERM, NULL);
	if(db_file == NULL)
	{
		fprintf(stderr, "gdbm error: %s\n", gdbm_strerror(gdbm_errno));
		perror(outfile);
		exit(6);
	}

	/* write some administrative data to the database */
	write_commondb_header(db_file, outfile);
	for(i = 0 ; i < num_dirs_to_visit; i++)
		write_commondb_dirinfo(db_file, dirs_to_visit[i]);

	/* purge non-matching chars to /dev/null */
	yyout = fopen(YYOUT_DEVICE, "w+");

	num_files--;

	/* register exit function if the scanner fails */
	atexit(scanner_fail);

	/* loop through all files in the filelist */
	for(i = 0; i <= num_files; i++)
	{
		/* Check to see if we are to ignore this file */
		if((num_ignore == 0 ? 1 : ignore_this_file(file_list[i])))
		{
			file = fopen(file_list[i], "r");
			if(!file)
			{
				perror(file_list[i]); 
				continue;
			}
			num_common_total = num_common_rejected = 0;
			num_common_accepted = 0;
			num_common_replaced = num_common_stored = 0;
			num_errors = num_warnings = 0;

			/* get the complete path to this file and store it */
			ParseFilename(file_list[i], curr_file, curr_path);
			if(full_names)
				sprintf(fullname, "%s%s", curr_path, curr_file);
			else
				sprintf(fullname, "%s", curr_file);

			/* data belonging to each common found in this file */
			content.dptr = fullname;
			content.dsize = strlen(fullname)+1;
			yyin = file;  
			if(!quiet) 
				printf("\nScanning %s\n", file_list[i]);
			rewind(yyin);
			/* go scan the file */
			yylex();
			YY_FLUSH_BUFFER;	/* clear scanner buffer */ 
			fclose(yyin);		/* close the input file */
			if(verbose) 		/* report if wanted */
			{ 
				printf("\n---- Stats for file %s (%i/%i)\n", 
					file_list[i], i+1, num_files+1);
				printf("commons found      : %i\n", 
					num_common_total);
				printf("duplicate commons  : %i\n", 
					num_common_replaced);
				printf("commons rejected   : %i\n", 
					num_common_rejected);
				printf("commons accepted   : %i\n", 
					num_common_accepted);
				printf("commons stored     : %i\n", 
					num_common_stored);
				printf("Scan warnings      : %i\n", 
					num_warnings);
				printf("Scan errors        : %i\n", 
					num_errors);
			}
			/* flush messages to stdout */
			fflush(stdout);
			num_total += num_common_total;
			num_total_replaced += num_common_replaced;
			num_total_rejected += num_common_rejected;
			num_total_accepted += num_common_accepted;
			num_total_stored   += num_common_stored;
			curr_file_num++;
		}
	}
	/* close /dev/null */
	fclose(yyout);

	/* report some statistics */
	if(!quiet)
	{
		printf("\n--- Total Statistics ---\n");
		printf("Directories visited: %i\n", num_dirs_to_visit);
		printf("Files searched     : %i\n", num_files+1);
		printf("Files ignored      : %i\n\n", ign_file_num);
		printf("commons found      : %i\n", num_total);
		printf("duplicate commons  : %i\n", num_total_replaced);
		printf("commons rejected   : %i\n", num_total_rejected);
		printf("commons accepted   : %i\n", num_total_accepted);
		printf("commons stored     : %i\n", num_total_stored);
		printf("\n------------------------\n");
	}

	/* write some more administrative data */
	write_commondb_update_info(db_file, num_total - num_total_rejected );

	if(reorganize)
	{
		if(!quiet)
			printf("Re-organizing database\n");
		if(gdbm_reorganize(db_file))
		{
			fprintf(stderr, "gdbm error: %s\n",
				gdbm_strerror(gdbm_errno));
			perror(outfile);
		}
	}
	gdbm_close(db_file);	/* close the database */
	db_file = NULL;

#ifdef __MSDOS__
	if(need_mem_info_for_msdos)
	{
		printf("\n------------------\n");
		printf("MSDOS Memory Usage\n\n");
		printf("Heap size is %u bytes\n", _heaplen);
		printf("Stack size is %u\ bytesn", _stklen);
		dir_mem = sizeof(dirs_to_visit);
		for(i = 0 ; i < num_dirs_to_visit; i++)
			dir_mem += strlen(dirs_to_visit[i]);
		printf("Memory used by dir list: %lu bytes\n", dir_mem);
		ext_mem = sizeof(ext_table);
		for(i = 0 ; i < num_extensions; i++)
			ext_mem += strlen(ext_table[i]);
		printf("Memory used by ext list: %lu bytes\n", ext_mem);
		ign_mem = sizeof(ignore_list);
		for(i = 0 ; i < num_ignore; i++)
			ign_mem += strlen(ignore_list[i]);
		printf("Memory used by ignore list: %lu bytes\n", ign_mem);
		file_mem = sizeof(file_list);
		for(i = 0 ; i < num_files; i++)
			file_mem += strlen(file_list[i]);
	 	printf("Memory used by file list: %lu bytes\n", file_mem);

		printf("Total memory used: %lu bytes\n",
			dir_mem + ext_mem + ign_mem + file_mem);
	}
#endif
	return(0);
}
