.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH GET_COMMON 1 "August 1996" Linux "ForUtil Fortran Tools"
.SH NAME
get_common \- get the name of a file where a f77 common is defined.

.SH SYNOPSIS
.B get_common [-chv] 
.BI \-d database 
.B common

.SH DESCRIPTION
.B get_common 
can be used to quickly see in what f77 include file a certain f77
common is defined. 
.B get_common 
queries a database generated with
.BR scan_commons (1).

.SH OPTIONS
.TP
.B "\-c"
case sensitive search, default is off.

.TP
.B "\-h, \-\-help"
Shows a short description of every option.

.TP
.B "\-v"
show database version information. This information consists 
of the name of the user that has created this database, the 
machine and system name where this database was created on, 
the date of the last update of this database, and the 
directories stored.

.TP
.B "\-\-version"
Shows the version number of 
.B get_common
.

.TP
.BI \-d database
Name of the database to query. If no database is given, the 
value of 
.B "COMMON_DATABASE"
is checked.

.TP
.B "common"
The name of the common you wish to locate. If this common is 
defined in multiple files, all files where this common is
defined will be shown.

.SH COMPATIBILITY
.B get_common 
has run under HP-UX 9 and 10, SGI IRIX 5.2 & 5.3, DEC OSF1, 
SunOs 4.1 and 4.3, Cray Unicos, IBM AIX 3.2 & 4.1, Linux and MSDOS 6.2. 
.B get_common 
also runs in a dos box under Windows 3.1, 3.11 and Win95.

.SH ENVIRONMENT
.TP
.B "COMMON_DATABASE"
Points to the location of a common database. This environment
variable is only used if the 
.BI \-d database
option is not given.

.SH DISTRIBUTION POLICY
All utilities in this fortran utility suite are distributed under
the GNU Public License.

.SH BUGS
If a bug occurs, it will most likely be generated by the MS-DOS
versions of these tools. This will be mainly due to the 640kb 
memory limit MS-DOS has.

If you think you have found a bug, you can send email to the author,
describing what the bug is, how you generated it and if you can
reproduce it. Also specify the platform where this bug occured.

.SH AUTHOR
.RS
.RE
Koen D'Hondt
.RS
.RE
ripley@xs4all.nl
.RS
.RE
(C)Copyright 1995-1996 by Ripley Software Development
.RE

.SH SEE ALSO
.BR scan_commons (1), 
.BR list_commons (1),
.BR fflow (1),
.BR ffscan (1),
.BR ftags (1)
